config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :calculations do
    resources :notes
  end
  
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calculation.rb
class Calculation < ApplicationRecord
    has_many :notes
    
    validates :first_name, presence: true, length: { minimum: 2 }
    validates :middle_name, presence: true, length: { minimum: 2 }
    validates :last_name, presence: true, length: { minimum: 2 }
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :calculation
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/calculations_controller.rb
class CalculationsController < ApplicationController
    def index
        @calculations = Calculation.all
    end
    
    def show
        @calculation = Calculation.find(params[:id])
    end
    
    def new
        @calculation = Calculation.new
    end

    def edit
        @calculation = Calculation.find(params[:id])
    end

    def create
        @calculation = Calculation.new(calculation_params)

        @calculation.birth_number = MainNumbersService.new(@calculation).birth_number
        @calculation.heart_number = MainNumbersService.new(@calculation).heart_number
        @calculation.figure_number = MainNumbersService.new(@calculation).figure_number
        @calculation.destiny_number = MainNumbersService.new(@calculation).destiny_number
        @calculation.reality_number = MainNumbersService.new(@calculation).reality_number
        @calculation.physical_aspect = MainNumbersService.new(@calculation).physical_aspect
        @calculation.physical_aspect_total = MainNumbersService.new(@calculation).physical_aspect_total
        @calculation.mental_aspect = MainNumbersService.new(@calculation).mental_aspect
        @calculation.mental_aspect_total = MainNumbersService.new(@calculation).mental_aspect_total
        @calculation.emotional_aspect = MainNumbersService.new(@calculation).emotional_aspect
        @calculation.emotional_aspect_total = MainNumbersService.new(@calculation).emotional_aspect_total
        @calculation.intuitive_aspect = MainNumbersService.new(@calculation).intuitive_aspect
        @calculation.intuitive_aspect_total = MainNumbersService.new(@calculation).intuitive_aspect_total


        if @calculation.save 
            redirect_to @calculation
        else
            render 'new'
        end    
    end

    def update
        @calculation = Calculation.find(params[:id])
        @calculation.attributes = calculation_params
        #@calculation.assign_attributes(calculation_params)

        @calculation.birth_number = MainNumbersService.new(@calculation).birth_number
        @calculation.heart_number = MainNumbersService.new(@calculation).heart_number
        @calculation.figure_number = MainNumbersService.new(@calculation).figure_number
        @calculation.destiny_number = MainNumbersService.new(@calculation).destiny_number
        @calculation.reality_number = MainNumbersService.new(@calculation).reality_number
        @calculation.physical_aspect = MainNumbersService.new(@calculation).physical_aspect
        @calculation.physical_aspect_total = MainNumbersService.new(@calculation).physical_aspect_total
        @calculation.mental_aspect = MainNumbersService.new(@calculation).mental_aspect
        @calculation.mental_aspect_total = MainNumbersService.new(@calculation).mental_aspect_total
        @calculation.emotional_aspect = MainNumbersService.new(@calculation).emotional_aspect
        @calculation.emotional_aspect_total = MainNumbersService.new(@calculation).emotional_aspect_total
        @calculation.intuitive_aspect = MainNumbersService.new(@calculation).intuitive_aspect
        @calculation.intuitive_aspect_total = MainNumbersService.new(@calculation).intuitive_aspect_total


        if @calculation.save
            redirect_to @calculation
        else
            render 'edit'
        end
    end 
    
    def destroy
        @calculation = Calculation.find(params[:id])
        @calculation.destroy

        redirect_to calculations_path
    end

    private
        def calculation_params
            params.require(:calculation).permit(:first_name, 
                                                :middle_name, 
                                                :last_name, 
                                                :date_of_birth)
        end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calculations_helper.rb
module CalculationsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/calculations/_form.html.erb
<%= form_with model: @calculation, local: true do |form| %>

    <% if @calculation.errors.any? %>
        <div id="error_explanation">
            <h2>
                <%= pluralize(@calculation.errors.count, "error") %> prohibited this calculation form
                being saved:
            </h2>
                <ul>
                    <% @calculation.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                    <% end %>
                </ul>
        </div>
    <% end %>

    <p>
        <%= form.label :first_name %><br>
        <%= form.text_field :first_name %>
    </p>

    <p>
        <%= form.label :middle_name %><br>
        <%= form.text_field :middle_name %>
    </p>

    <p>
        <%= form.label :last_name %><br>
        <%= form.text_field :last_name %>
    </p>

      <p>
        <%= form.label :date_of_birth %><br>
        <%= form.date_select(:date_of_birth, :start_year => 1905) %>
    </p>

    <p>
        <%= form.submit %>
    </p>
<% end %>

app/views/calculations/edit.html.erb
<h1>Editing calculation</h1>

<%= render 'form' %>

<p>
    <%= link_to 'Back', calculations_path %>
</p>

app/views/calculations/index.html.erb
<h1>The List of Calculations</h1>

<table>
    <tr>
        <th>Name</th>
        <th>Date Of Birth:</th>
        <thcolspan="2"></th>
    </tr>

    <% @calculations.each do |calculation| %>
        <tr>
            <td><%= calculation.first_name %> <%= calculation.middle_name %> <%= calculation.last_name %></td>
            <td><%= calculation.date_of_birth %></td>
            <td><%= link_to 'Show', calculation_path(calculation) %></td>
            <td><%= link_to 'Edit', edit_calculation_path(calculation) %></td>
            <td><%= link_to 'Destroy', calculation_path(calculation),
                    method: :delete,
                    data: { confirm: 'Are you sure?' }%></td>
        </tr>
    <% end %>
</table>    

<p>
    <%= link_to 'New calculation', new_calculation_path %>
</p>
        

app/views/calculations/new.html.erb
<h1>New calculation</h1/>

<%= render 'form' %>

<p>
    <%= link_to 'Back', calculations_path %>
</p>

app/views/calculations/show.html.erb
<p>
    <strong>Имя:</strong>
    <%= @calculation.first_name %>
</p>

<p>
    <strong>Отчество:</strong>
    <%= @calculation.middle_name %>
</p>

<p>
    <strong>Фамилия:</strong>
    <%= @calculation.last_name %>
</p>

<p>
    <strong>Дата рождения:</strong>
    <%= @calculation.date_of_birth %>
</p>

<p>
    <strong>Число рождения:</strong>
    <%= @calculation.birth_number %>
</p>

<p>
    <strong>Число судьбы:</strong>
    <%= @calculation.destiny_number %>
</p>

<p>
    <strong>Число сердца:</strong>
    <%= @calculation.heart_number %>
</p>

<p>
    <strong>Число образа:</strong>
    <%= @calculation.figure_number %>
</p>

<p>
    <strong>Число реальности:</strong>
    <%= @calculation.reality_number %>
</p>

<p>
    <strong>Физический план:</strong>
    <%= @calculation.physical_aspect %>
</p>

<p>
    <strong>Суммарное значение для физического плана:</strong>
    <%= @calculation.physical_aspect_total %>
</p>

<p>
    <strong>Ментальный план:</strong>
    <%= @calculation.mental_aspect %>
</p>

<p>
    <strong>Суммарное значение для ментального плана:</strong>
    <%= @calculation.mental_aspect_total %>
</p>

<p>
    <strong>Эмоциональный план:</strong>
    <%= @calculation.emotional_aspect %>
</p>

<p>
    <strong>Суммарное значение для эмоционального плана:</strong>
    <%= @calculation.emotional_aspect_total %>
</p>

<p>
    <strong>Интуитивный план:</strong>
    <%= @calculation.intuitive_aspect %>
</p>

<p>
    <strong>Суммарное значение для интуитивного плана:</strong>
    <%= @calculation.intuitive_aspect_total %>
</p>


<%= link_to 'Edit', edit_calculation_path(@calculation) %>
<%= link_to 'Back', calculations_path %>
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Num</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>